[package]
name = "derive_examples"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
layout-derive = { path = "../" }
layout-trait = { path = "../../layout-trait" }
heapless = "0.7.16"
esp32c3 = "0.14.0"
